Run gradle wrapper \

Welcome to Gradle 8.7!

Here are the highlights of this release:
 - Compiling and testing with Java 22
 - Cacheable Groovy script compilation
 - New methods in lazy collection properties

For more details see https://docs.gradle.org/8.7/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.7/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 

> Configure project :
Fabric Loom: 1.6.5

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'allmusic-client'.
> Could not resolve all dependencies for configuration ':mappings'.
   > Could not find net.fabricmc:yarn:1.21.7+build.15.
     Searched in the following locations:
       - file:/home/runner/work/AllMusic_Client/AllMusic_Client/.gradle/loom-cache/remapped_mods/net/fabricmc/yarn/1.21.7+build.15/yarn-1.21.7+build.15.pom
       - file:/home/runner/.gradle/caches/fabric-loom/minecraftMaven/net/fabricmc/yarn/1.21.7+build.15/yarn-1.21.7+build.15.pom
       - file:/home/runner/work/AllMusic_Client/AllMusic_Client/.gradle/loom-cache/minecraftMaven/net/fabricmc/yarn/1.21.7+build.15/yarn-1.21.7+build.15.pom
       - https://maven.fabricmc.net/net/fabricmc/yarn/1.21.7+build.15/yarn-1.21.7+build.15.pom
       - https://libraries.minecraft.net/net/fabricmc/yarn/1.21.7+build.15/yarn-1.21.7+build.15.pom
       - https://libraries.minecraft.net/net/fabricmc/yarn/1.21.7+build.15/yarn-1.21.7+build.15-v2.jar
       - https://repo.maven.apache.org/maven2/net/fabricmc/yarn/1.21.7+build.15/yarn-1.21.7+build.15-v2.jar
       - https://repo.maven.apache.org/maven2/net/fabricmc/yarn/1.21.7+build.15/yarn-1.21.7+build.15.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 25s
Error: Process completed with exit code 1.
