name: Build AllMusic 1.21.7 Fabric

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: 手动安装Gradle 8.7
        run: |
          # 下载并解压Gradle
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip
          
          # 显式设置Gradle路径（使用绝对路径）
          export GRADLE_INSTALL_DIR=$(pwd)/gradle-8.7
          echo "Gradle安装路径: $GRADLE_INSTALL_DIR"
          
          # 验证Gradle可执行文件存在
          if [ ! -f "$GRADLE_INSTALL_DIR/bin/gradle" ]; then
              echo "错误：未找到Gradle可执行文件"
              exit 1
          fi

      - name: 生成Gradle Wrapper
        run: |
          # 使用显式路径执行Gradle
          $GRADLE_INSTALL_DIR/bin/gradle wrapper \
            --gradle-version 8.7 \
            --distribution-type bin \
            --no-daemon

      - name: 验证Wrapper文件
        run: |
          if [ ! -f "gradlew" ]; then
              echo "错误：gradlew文件未生成"
              exit 1
          fi
          chmod +x gradlew
          ./gradlew --version  # 验证wrapper是否可用

      - name: 配置版本参数
        run: |
          cat > gradle.properties << 'EOF'
          minecraft_version=1.21.7
          yarn_mappings=1.21.7+build.15
          loader_version=0.16.15
          fabric_version=0.110.1+1.21.7
          mod_version=3.0.7
          maven_group=com.coloryr
          archives_base_name=allmusic-client
          EOF

      - name: 执行构建
        run: ./gradlew clean build --stacktrace

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: allmusic-1.21.7-fabric
          path: build/libs/*.jar
