name: Build AllMusic 1.21.7 Fabric

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FABRIC_REPO_URL: "https://maven.fabricmc.net/"
      YARN_VERSION: "1.21.7+build.15"
      GRADLE_VERSION: "8.7"
      # 明确项目根目录（与检出路径一致）
      PROJECT_ROOT: "."

    steps:
      - name: 检出代码（确保完整检出所有文件）
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史，避免文件缺失

      - name: 验证工作目录文件
        run: |
          echo "当前工作目录: $(pwd)"
          ls -la  # 列出所有文件，确认是否有源码文件
          # 若输出中没有你的Java源码文件，说明检出路径错误

      - name: 清理缓存
        run: |
          rm -rf ~/.gradle/caches/modules-2/files-2.1/net.fabricmc/yarn/
          rm -rf ./.gradle/loom-cache/

      - name: 设置Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle
          # 修正缓存路径：使用通配符匹配可能的文件位置
          cache-dependency-path: "**/*.gradle"

      - name: 安装Gradle
        run: |
          wget "https://services.gradle.org/distributions/gradle-${{ env.GRADLE_VERSION }}-bin.zip" -O gradle.zip
          unzip -q gradle.zip
          export GRADLE_HOME=$(pwd)/gradle-${{ env.GRADLE_VERSION }}
          echo "$GRADLE_HOME/bin" >> $GITHUB_PATH
          gradle --version

      - name: 创建Gradle配置文件（确保在项目根目录）
        run: |
          # 明确在项目根目录创建文件
          cd ${{ env.PROJECT_ROOT }}
          
          cat > settings.gradle << EOF
          pluginManagement {
              repositories {
                  maven { url "${{ env.FABRIC_REPO_URL }}" }
                  gradlePluginPortal()
              }
          }
          rootProject.name = "allmusic-client"
          EOF

          cat > build.gradle << EOF
          plugins {
              id 'fabric-loom' version '1.6.5'
              id 'maven-publish'
          }

          repositories {
              maven { url "${{ env.FABRIC_REPO_URL }}" }
              mavenCentral()
          }

          version = project.mod_version
          group = project.maven_group

          dependencies {
              minecraft "com.mojang:minecraft:\${minecraft_version}"
              mappings "net.fabricmc:yarn:${{ env.YARN_VERSION }}:v2"
              modImplementation "net.fabricmc:fabric-loader:\${loader_version}"
              modImplementation "net.fabricmc.fabric-api:fabric-api:\${fabric_version}"
          }

          tasks.withType(JavaCompile).configureEach {
              options.release = 21
              options.encoding = "UTF-8"
          }

          loom {
              remapJar { enabled = true }
          }
          EOF

          cat > gradle.properties << EOF
          minecraft_version=1.21.7
          yarn_mappings=${{ env.YARN_VERSION }}
          loader_version=0.16.15
          fabric_version=0.110.1+1.21.7
          mod_version=3.0.7
          maven_group=com.coloryr
          archives_base_name=allmusic-client
          EOF

          # 确认文件已创建
          ls -la *.gradle
          ls -la gradle.properties

      - name: 生成Gradle Wrapper
        run: |
          cd ${{ env.PROJECT_ROOT }}
          gradle wrapper \
            --gradle-version ${{ env.GRADLE_VERSION }} \
            --distribution-type bin \
            --no-daemon

      - name: 执行构建
        run: |
          cd ${{ env.PROJECT_ROOT }}
          chmod +x gradlew
          ./gradlew clean build --stacktrace --info

      - name: 上传构建产物
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AllMusic-1.21.7-Fabric
          path: ${{ env.PROJECT_ROOT }}/build/libs/*.jar  # 明确产物路径

      - name: 上传错误日志（修正路径格式）
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-errors
          path: |
            ${{ env.PROJECT_ROOT }}/build/reports/**/*
            ~/.gradle/caches/**/*  # 修正：去掉路径中的空格，使用通配符
