name: Build AllMusic 1.21.7 Fabric

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Java环境（Java 21）
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: 生成Gradle Wrapper文件
      run: gradle wrapper --gradle-version 8.7

    - name: 配置1.21.7版本参数
      run: |
        # 替换现有配置而非追加（避免重复配置）
        echo "minecraft_version=1.21.7" > gradle.properties
        echo "yarn_mappings=1.21.7+build.12" >> gradle.properties
        echo "loader_version=0.16.15" >> gradle.properties
        echo "fabric_version=0.109.0+1.21.7" >> gradle.properties
        echo "mod_version=3.0.7" >> gradle.properties
        echo "maven_group=com.coloryr" >> gradle.properties
        echo "archives_base_name=allmusic-client" >> gradle.properties

    - name: 执行构建（显示详细日志）
      run: |
        chmod +x gradlew
        ./gradlew clean build --stacktrace  # 添加--stacktrace显示详细错误

    - name: 上传构建产物（若成功）
      if: success()  # 仅当构建成功时上传
      uses: actions/upload-artifact@v4
      with:
        name: allmusic-1.21.7-fabric
        path: build/libs/*.jar
