name: Build AllMusic 1.21.7 Fabric

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Java环境（Java 21）
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: 生成Gradle Wrapper文件（包含gradlew）
      run: |
        # 手动生成gradlew和相关配置文件，适配8.7版本
        gradle wrapper --gradle-version 8.7

    - name: 配置1.21.7版本参数
      run: |
        echo "minecraft_version=1.21.7" >> gradle.properties
        echo "yarn_mappings=1.21.7+build.12" >> gradle.properties
        echo "loader_version=0.16.15" >> gradle.properties
        echo "fabric_version=0.109.0+1.21.7" >> gradle.properties

    - name: 执行构建命令
      run: |
        chmod +x gradlew  # 赋予执行权限
        ./gradlew clean build

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: allmusic-1.21.7-fabric
        path: build/libs/*.jar
